# Graphical settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2 # the width of the lines that draw the player's ship

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
# Exhaust particle system
EXHAUST_PARTICLE_LIFETIME_MIN = 0.3  # seconds
EXHAUST_PARTICLE_LIFETIME_MAX = 0.8  # seconds
EXHAUST_PARTICLE_SIZE_MIN = 1        # pixels
EXHAUST_PARTICLE_SIZE_MAX = 4        # pixels
EXHAUST_SPREAD_ANGLE = 30            # degrees from backward vector
EXHAUST_EMISSION_RATE_MIN = 2        # particles per frame (low thrust)
EXHAUST_EMISSION_RATE_MAX = 5        # particles per frame (full thrust)
EXHAUST_MAX_PARTICLES = 150          # hard cap on simultaneous particles
EXHAUST_PARTICLE_SPEED_MIN = 80      # px/s
EXHAUST_PARTICLE_SPEED_MAX = 200     # px/s
EXHAUST_COLORS = [(100, 149, 237), (0, 191, 255), (135, 206, 250)]  # blue ion range
EXHAUST_INTENSITY_CAP = 2.0          # seconds to reach full intensity

# Audio settings
AUDIO_SAMPLE_RATE = 44100
AUDIO_COMBO_TIMEOUT = 0.5  # seconds between hits to maintain combo
# A minor pentatonic scale frequencies (Hz)
AUDIO_SCALE_A_MINOR_PENTATONIC = [440.0, 523.25, 587.33, 659.25, 783.99]

AUDIO_COMBO_BASE_DURATION = 0.1
AUDIO_COMBO_DURATION_STEP = 0.1
AUDIO_DECAY_RATE = 3.0

# Explosion particle effects
EXPLOSION_PARTICLE_LIFETIME_MIN = 0.2  # seconds
EXPLOSION_PARTICLE_LIFETIME_MAX = 0.5  # seconds
EXPLOSION_PARTICLE_SPEED_MIN = 200     # px/s
EXPLOSION_PARTICLE_SPEED_MAX = 400     # px/s
EXPLOSION_PARTICLE_SIZE_MIN = 1        # pixels
EXPLOSION_PARTICLE_SIZE_MAX = 3        # pixels
# Explosion particle counts by asteroid size
EXPLOSION_COUNT_LARGE_MIN = 20         # large asteroids (radius >= 40)
EXPLOSION_COUNT_LARGE_MAX = 30
EXPLOSION_COUNT_MEDIUM_MIN = 10        # medium asteroids (radius 20-39)
EXPLOSION_COUNT_MEDIUM_MAX = 15
EXPLOSION_COUNT_SMALL_MIN = 5          # small asteroids (radius < 20)
EXPLOSION_COUNT_SMALL_MAX = 8

# Gun settings
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_VELOCITY_MULTIPLIER = 1.2

# Game settings
GAME_OVER_TEXT_SIZE = 60
GAME_OVER_SUBTEXT_SIZE = 30
GAME_OVER_RETRY_TEXT_SIZE = 25

# Logging
LOG_MAX_SECONDS = 16
LOG_FPS = 60
LOG_SPRITE_SAMPLE_LIMIT = 10

# Delta time
MAX_DELTA_TIME = 0.05

# Leaderboard
LEADERBOARD_TITLE_SIZE = 50
LEADERBOARD_ENTRY_SIZE = 30
LEADERBOARD_PROMPT_SIZE = 25
LEADERBOARD_MAX_NAME_LENGTH = 12
LEADERBOARD_MAX_SCORES = 10

# Menu
MENU_DEFAULT_FONT_SIZE = 30
MENU_SECTION_PADDING = 20
MENU_ELEMENT_PADDING = 5
MENU_HORIZONTAL_MARGIN = 50

# Events
EVENT_QUIT = "quit"
EVENT_RETRY = "retry"
EVENT_MENU = "menu"

# Stars
STAR_COUNT = 100
STAR_COLOR = (255, 255, 255)
STAR_MIN_SIZE = 1
STAR_MAX_SIZE = 3
STAR_TWINKLE_SPEED = 2.0

# Hyperdrive
HYPERDRIVE_DURATION = 3.0
HYPERDRIVE_STAR_COUNT = 300
HYPERDRIVE_FOV = 400
HYPERDRIVE_SHIP_FLY_IN_TIME = 0.2
HYPERDRIVE_COLOR = (255, 255, 255)
HYPERDRIVE_TRANSITION_TIME = 1.5
HYPERDRIVE_WARP_START_TIME = 0.6

# Music system
MUSIC_BPM = 120
MUSIC_STEPS_PER_BAR = 16
MUSIC_SAMPLE_RATE = 44100

# Note frequencies (A minor pentatonic for bass - one octave below combo scale)
MUSIC_BASS_A2 = 110.0
MUSIC_BASS_C3 = 130.81
MUSIC_BASS_D3 = 146.83
MUSIC_BASS_E3 = 164.81
MUSIC_BASS_G3 = 196.00
MUSIC_BASS_A3 = 220.0

# Chord roots
MUSIC_CHORD_AM = 110.0
MUSIC_CHORD_C = 130.81
MUSIC_CHORD_DM = 146.83
MUSIC_CHORD_EM = 164.81
