# Graphical settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2 # the width of the lines that draw the player's ship

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
# Exhaust particle system
EXHAUST_PARTICLE_LIFETIME_MIN = 0.3  # seconds
EXHAUST_PARTICLE_LIFETIME_MAX = 0.8  # seconds
EXHAUST_PARTICLE_SIZE_MIN = 1        # pixels
EXHAUST_PARTICLE_SIZE_MAX = 4        # pixels
EXHAUST_SPREAD_ANGLE = 30            # degrees from backward vector
EXHAUST_EMISSION_RATE_MIN = 2        # particles per frame (low thrust)
EXHAUST_EMISSION_RATE_MAX = 5        # particles per frame (full thrust)
EXHAUST_MAX_PARTICLES = 150          # hard cap on simultaneous particles
EXHAUST_PARTICLE_SPEED_MIN = 80      # px/s
EXHAUST_PARTICLE_SPEED_MAX = 200     # px/s
EXHAUST_COLORS = [(100, 149, 237), (0, 191, 255), (135, 206, 250)]  # blue ion range
EXHAUST_INTENSITY_CAP = 2.0          # seconds to reach full intensity

# Gun settings
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_VELOCITY_MULTIPLIER = 1.2

# Game settings
GAME_OVER_TEXT_SIZE = 60
GAME_OVER_SUBTEXT_SIZE = 30
GAME_OVER_RETRY_TEXT_SIZE = 25

# Logging
LOG_MAX_SECONDS = 16
LOG_FPS = 60
LOG_SPRITE_SAMPLE_LIMIT = 10

# Delta time
MAX_DELTA_TIME = 0.05

# Leaderboard
LEADERBOARD_TITLE_SIZE = 50
LEADERBOARD_ENTRY_SIZE = 30
LEADERBOARD_PROMPT_SIZE = 25
LEADERBOARD_MAX_NAME_LENGTH = 12
LEADERBOARD_MAX_SCORES = 10

# Menu
MENU_DEFAULT_FONT_SIZE = 30
MENU_SECTION_PADDING = 20
MENU_ELEMENT_PADDING = 5
MENU_HORIZONTAL_MARGIN = 50

# Events
EVENT_QUIT = "quit"
EVENT_RETRY = "retry"
EVENT_MENU = "menu"

# Stars
STAR_COUNT = 100
STAR_COLOR = (255, 255, 255)
STAR_MIN_SIZE = 1
STAR_MAX_SIZE = 3
STAR_TWINKLE_SPEED = 2.0

# Hyperdrive
HYPERDRIVE_DURATION = 3.0
HYPERDRIVE_STAR_COUNT = 300
HYPERDRIVE_FOV = 400
HYPERDRIVE_SHIP_FLY_IN_TIME = 0.2
HYPERDRIVE_COLOR = (255, 255, 255)
HYPERDRIVE_TRANSITION_TIME = 1.5
HYPERDRIVE_WARP_START_TIME = 0.6