# Graphical settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2 # the width of the lines that draw the player's ship

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Gun settings
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_VELOCITY_MULTIPLIER = 1.2

# Game settings
GAME_OVER_TEXT_SIZE = 60
GAME_OVER_SUBTEXT_SIZE = 30
GAME_OVER_RETRY_TEXT_SIZE = 25

# Logging
LOG_MAX_SECONDS = 16
LOG_FPS = 60
LOG_SPRITE_SAMPLE_LIMIT = 10

# Delta time
MAX_DELTA_TIME = 0.05

# Leaderboard
LEADERBOARD_TITLE_SIZE = 50
LEADERBOARD_ENTRY_SIZE = 30
LEADERBOARD_PROMPT_SIZE = 25
LEADERBOARD_MAX_NAME_LENGTH = 12
LEADERBOARD_MAX_SCORES = 10

# Menu
MENU_DEFAULT_FONT_SIZE = 30